[project]
name = "ros_workspace"
channels = ["conda-forge", "robostack-staging", "https://prefix.dev/ruben-arts"]
platforms = ["linux-64"]           

[tasks]
sim = "ros2 run turtlesim turtlesim_node"
# Get back ros2 by ensuring python files are
# also available in `$PREFIX/lib/$PACKAGE_NAME`
talker = "talker"
navigator = "ros2 run navigator navigator"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
#navigator = { channel = "https://prefix.dev/ruben-arts", version = "0.0.2" }
navigator = { path = "src/navigator" }
talker = { path = "src/talker" }
