[workspace]
channels = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/conda-forge", "https://prefix.dev/robostack-staging"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[package]
name = "undefined"
version = "0.0.0"

[package.build.backend]
name = "pixi-build-ros"
git = "https://github.com/ruben-arts/pixi-build-backends"
subdirectory = "backends/pixi-build-ros"
branch = "fix/ros-backend"


[package.build.config]
distro = "humble"
debug_dir = "pixi-build-debug" 
