package:
  name: navigator
  version: 0.0.1

source:
  path: .

build:
  number: 0
  script: ros-conda-build.sh

requirements:
  build:
    - ros-conda-build-support
    - ${{ compiler('cxx') }} 
    - cmake
    - ninja
    - make
    - coreutils
  host: 
    - cmake
    - ninja
    - make
    - coreutils
    - pkg-config
    - ros-humble-ament-cmake
    - ros-humble-ament-index-cpp
    - ros-humble-rclcpp
    - ros-humble-rclcpp-action
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-std-msgs
    - ros-humble-geometry-msgs
    - ros-humble-turtlesim
    - ros2-distro-mutex 0.5 humble
  run :
    - ros-humble-rclcpp
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-geometry-msgs
    - ros-humble-turtlesim
    - ros2-distro-mutex 0.5 humble

about:
  description: Example ros package which includes a navigation server

