[project]
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "talker"
platforms = ["win-64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[host-dependencies]
setuptools = "<=58.2.0"

[dependencies]
ros-humble-rclpy = ">=3.3.11,<4"
ros-humble-geometry-msgs = ">=4.2.3,<5"
