[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "talker"
version = "0.0.0"
description = "TODO: Package description"
readme = "README.md"
license = { text = "TODO: License declaration" }
authors = [{ name = "rarts", email = "ruben.arts@hotmail.com" }]
maintainers = [{ name = "rarts", email = "ruben.arts@hotmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
talker = "talker.talker:main"

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
include = ["talker"]

[tool.setuptools.data-files]
"share/ament_index/resource_index/packages" = ["resource/talker"]
"share/talker" = ["package.xml"]

[tool.pixi.project]
platforms = ["win-64", "osx-arm64", "linux-64"]
channels = ["conda-forge", "robostack-staging"]

[tool.pixi.build]
build-backend = "pixi-build-python"
dependencies = []

[tool.pixi.host-dependencies]
setuptools = ">=73.0.0"
uv = "0.4.12"

[tool.pixi.dependencies]
ros-humble-rclpy = ">=3.3.11,<4"
ros-humble-geometry-msgs = ">=4.2.3,<5"
ros-humble-turtlesim = ">=1.4.2,<2"
