package:
  name: ros-humble-talker
  version: 0.0.5

source:
  path: .

build:
  number: 0
  script: py-ros-conda-build.sh


requirements:
  build:
    - ros-conda-build-support
    - python 3.11.*
    - setuptools <=58.2.0
    - ${{ compiler('cxx') }} 
    - cmake
    - ninja
    - colcon-core
    - colcon-ros
    - make
    - coreutils
  host: 
    - python 3.11.*
    - setuptools <=58.2.0
    - colcon-core
    - colcon-ros
    - ros-humble-ament-package
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros2-distro-mutex 0.5 humble
  run :
    - python 3.11.*
    - ros-humble-rclpy
    - ros-humble-ament-package
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros2-distro-mutex 0.5 humble

about:
  description: Example ros package which includes a talker cli app

