package:
  name: ros-conda-build-support
  version: 0.0.1

build:
  script:
    - mkdir -p $PREFIX/bin
    - cp $RECIPE_DIR/build.sh $PREFIX/bin/ros-conda-build.sh
    - chmod +x $PREFIX/bin/ros-conda-build.sh
    - cp $RECIPE_DIR/build-python.sh $PREFIX/bin/py-ros-conda-build.sh
    - chmod +x $PREFIX/bin/py-ros-conda-build.sh